config/routes.rb
MusicApp::Application.routes.draw do

  resources :users, only: [:new, :create, :edit, :update, :show] do

    collection do
      get 'activate'
    end

  end

  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:index, :new, :create]
  end
  resources :albums, only: [:show, :new, :create, :destroy, :edit, :update] do
    resources :tracks, only: [:index, :new, :create]
  end

  resources :tracks, only: [:edit, :update, :destroy, :show]

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :band_id, :category, :name

  belongs_to :band,
  foreign_key: :band_id

  has_many :tracks, :dependent => :destroy,
  foreign_key: :album_id

end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name

  has_many :albums, :dependent => :destroy,
  foreign_key: :band_id

  has_many :tracks,
  through: :albums, source: :tracks
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user,
  foreign_key: :user_id

  belongs_to :track,
  foreign_key: :track_id
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :album_id, :category, :name, :lyrics

  belongs_to :album,
  foreign_key: :album_id

  has_one :band, through: :album, source: :band

  has_many :notes,
  foreign_key: :track_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_reader :password
  attr_accessible :email, :password
  after_initialize :ensure_session_token
  after_initialize :ensure_activation_token

  has_many :notes,
  foreign_key: :user_id

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_activation_token
    self.activation_token ||= SecureRandom::urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token
    self.session_token = SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    if user.is_password?(password)
      user
    else
      nil
    end
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index

  end

  def show
    @album = Album.find(params[:id])
    @album_tracks = @album.tracks
    @album_band = @album.band
  end

  def new
    @bands = Band.all
    @cur_band = Band.find(params[:band_id])
    @album = Album.new
  end

  def create
    @album = Album.new(params[:album])
    @album.save!
    redirect_to album_url(@album)
  end

  def edit
    @bands = Band.all
    @album = Album.find(params[:id])


    @cur_band = @album.band

  end

  def update
    @album = Album.find(params[:id])

    if @album.update_attributes(params[:album])
      redirect_to album_url(@album)
    else
      render :json => @album.errors.full_messages
    end

  end

  def destroy

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  protect_from_forgery
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index

  end

  def show
    @band = Band.find(params[:id])
    @band_albums = @band.albums
    @band_tracks = @band.tracks
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(params[:band])

    if @band.save
      redirect_to band_url(@band)
    else
      render :json => @band.errors.full_messages
    end

  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(params[:band])
      redirect_to band_url(@band)
    else
      render :json => @band.errors.full_messages
    end
  end

  def destroy

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user.nil?
      raise "wrongo!" #change
    elsif @user.activated == false
      raise "Please activate"
    else
      login_user!(@user)
    end
  end

  def destroy
    @user = current_user
    session[:session_token] = nil
    @user.reset_session_token
    redirect to users_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def index

  end

  def show

    @track = Track.find(params[:id])
    #should link to the Album and Band.
    @track_album = @track.album
    @track_band = @track.band

  end

  def new
    @albums = Album.all
    @track = Track.new
    @cur_album = Album.find(params[:album_id])
  end

  def create
    @track = Track.new(params[:track])
    if @track.save
      redirect_to track_url(@track)
    else
      render :json => @track.errors.full_messages
    end
  end

  def edit
    @albums = Album.all
    @track = Track.find(params[:id])
    @cur_album = @track.album
  end

  def update
    @track = Track.find(params[:id])
    if @track.update_attributes(params[:track])
      redirect_to track_url(@track)
    else
      render :json => @track.errors.full_messages
    end
  end

  def destroy

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index

  end

  def create
    @user = User.new(params[:user])
    @user.save!

    msg = UserMailer.activation_email(@user)
    msg.deliver!

    login_user!(@user)
  end

  def show
    @user = User.find(params[:id])
  end

  def activate
    @user = User.find_by_activation_token(params[:activation_token])

    if @user.nil?
      render :json => @user.errors.full_messages
    else
      @user.activated == true
      redirect_to user_url(@user)
    end
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login_user!(user)
    user.reset_session_token
    session[:session_token] = user.session_token
    fail
    redirect_to user_url(user)
  end

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    current_user.nil? ? false : true
  end

end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<% action_url = (action == :new) ? band_albums_url(cur_band.id) : album_url(cur_band.id) %>

<form action="<%= action_url %>" method="POST">
  <% if action == :edit %>
  <input type="hidden" name="_method" value="PUT">
  <% end %>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="album_name">Album name</label>
  <input type="text" name="album[name]" id="album_name" value="<%= album.name %>">

  <br>

  <select name="album[band_id]" id="album_band_id">
    <% bands.each do |band| %>
    <option value="<%= "#{band.id}" %>" <%= "selected" if (album.band_id == band.id) %>>
      <%= "#{band.id} - #{band.name}"   %>
    </option>
    <% end%>
  </select>

  <br>
  Album type:
  <input type="radio" name="album[category]" value="live" id="album_type_live" <%= "checked" if album.category == "live" %>>
  <label for="album_type_live">Live</label></input>
  <input type="radio" name="album[category]" value="studio" id="album_type_studio" <%= "checked" if album.category == "studio" %>><label for="album_type_studio">

    Studio</label></input>
  <br>
  <input type="submit" value="Submit">
</form>

app/views/albums/edit.html.erb
<h3> Edit Album</h3>

<%= render "form", :cur_band => @cur_band, :bands => @bands, :album => @album, :action => :edit %>

app/views/albums/new.html.erb
<h3> Create a new album </h3>

<%= render "form", :cur_band => @cur_band, :bands => @bands, :album => @album, :action => :new %>

app/views/albums/show.html.erb
You are in the album <%= "#{@album.name}" %> for <%= link_to @album_band.name, band_url(@album_band) %> with category <%= "#{@album.category}" %>


<br>
Track listing

<ul>
<% @album_tracks.each do |track| %>
<li><%= link_to "#{track.name}", track_url(track) %>
</li>

<% end %>
</ul>


<!-- link to band and tracks -->

app/views/bands/_form.html.erb
<% action_url = (action == :new) ? bands_url : band_url(band) %>

<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
  <input type="hidden" name="_method" value="put">
  <% end %>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">


  <label for="band_name">Band name:</label>
  <input type="text" name="band[name]" id="band_name" value="<%= band.name %>">

  <input type="submit" value="Submit">


</form>

app/views/bands/edit.html.erb
<h3> Edit your band </h3>

<%= render "form", :band => @band, :action => :edit %>

app/views/bands/new.html.erb
<h3> Create a new band </h3>

<%= render "form", band: @band, action: :new %>

app/views/bands/show.html.erb
<%= @band.name %> has the following albums:

<ul>
  <% unless @band_albums.nil? %>
  <%= @band_albums.count %>

<% @band_albums.each do |album| %>
<li><%= link_to album.name, album_url(album) %></li>
<% end %>

<% end %>
</ul>
<br>
<br>
This band has the following tracks:
<ul>
  <% unless @band_tracks.nil? %>
  <% @band_tracks.each do |track| %>
  <li><%= link_to track.name, track_url(track) %></ul>
  <% end %>
  <% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <!-- ><%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %> -->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tracks/_form.html.erb
<%#= render "form", :albums => @albums, :cur_album => @cur_album, :track => @track, :action => :edit %>

<% action_url = (action == :new) ? album_tracks_url(cur_album) : track_url(track) %>

<form action="<%= action_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <% if action == :edit %>
  <input type="hidden" name="_method" value="put">
  <% end %>

  <label for="track_name">Track name:</label>
  <input type="text" name="track[name]" id="track_name" value="<%= "#{track.name}" %>">

  <label for="track_album_id">Select album</label>
  <select name="track[album_id]" id="track_album_id">
    <% albums.each do |album| %>
    <option value="<%= "#{album.id}" %>" <%= "selected" if album.id == track.album_id %>> <%= "#{album.id} - #{album.name}" %> </option>
    <% end %>
  </select>
  <br>

  Track category:
  <input type="radio" name="track[category]" id="track_category_regular" value="regular" <%= "checked" if track.category == "regular" %>>
  <label for="track_category_regular">Regular</label>

  <input type="radio" name="track[category]" id="track_category_bonus" value="bonus"><label for="track_category_bonus" <%= "checked" if track.category == "bonus" %>>Bonus</label>
  <br>

  <label for="track_lyrics">lyrics</label>
  <input type="textarea" rows="10" cols="50" name="track[lyrics]" id="track_lyrics" value="<%= "#{track.lyrics}" %>"></input>

  <input type="submit">

</form>

app/views/tracks/edit.html.erb
<h3>Edit track</h3>

<%= render "form", :albums => @albums, :cur_album => @cur_album, :track => @track, :action => :edit %>

app/views/tracks/new.html.erb
<h3>Create new track</h3>

<%= render "form", :albums => @albums, :cur_album => @cur_album, :track => @track, :action => :new %>

app/views/tracks/show.html.erb
You are looking at <%= @track.name %> from <%= link_to @track_album.name, album_url(@track_album) %> by <%= link_to @track_band.name, band_url(@track_band) %> with category <%= "#{@track.category}"%>
<br>
Here are the lyrics:
<br>
<%= "#{@track.lyrics}"%>
<br>
<br>
<br>

app/views/users/index.html.erb
Placeholder...

app/views/users/new.html.erb
<form action="<%= users_url %>" method="POST">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="user_email">Email: </label>
  <input type="text" name="user[email]" id="user_email">

  <label for="user_password">Password: </label>
  <input type="password" name="user[password]" id="user_password">

  <input type="submit" value="Create user">

</form>

app/views/users/show.html.erb
Hello, <%= "#{@user.email}" %>